### ISSUE TITLE
Add copyright information

### ISSUE THREAD

**Issue by zumbi** [14rcole/gopopulate#2]
I would like to package and distribute this software in Debian as it is a debos (https://github.com/go-debos/debos) tool dependency due to being used to test github.com/ostreedev/ostree-go.

Could you please add copyright information for your code?

It would also be great if README.md is a bit more descriptive.

Thanks for your work!

**Comment by 14rcole** [comment]
Hi @zumbi, sorry for the delay.  I just added a license.  I'll flesh out the README a bit more as well

**Comment by zumbi** [comment]
That is excellent news! Thanks very much for adding license! I'll close this issue for now and I am looking into packaging it for Debian in near future.
Best regards
